name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    environment: nuget.org

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet build Triggr/Triggr.csproj --configuration Release -warnaserror

      - name: Pack
        run: dotnet pack Triggr/Triggr.csproj --configuration Release --no-build --output ./nupkg

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: DmytroKosenko

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
